name: Test site speed
on: [push, pull_request]
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: Tedyst/lighthouse-action@feature-deployment
        with:
          url: 'https://stoicatedy.ovh'
      - uses: actions/upload-artifact@master
        with:
          name: report
          path: './report'